### ISSUE TITLE
Config feature

### ISSUE THREAD

**Issue by mrniddala** [onebeastchris/fabricgeyserplayerheads#3]
Hello, I would like to disable this feature "if killed by player: adds "killed by [player]" in the lore of the item!".
Great mod - greetings.

**Comment by onebeastchris** [comment]
Hey! Thanks for reaching out.
A config feature is planned, unfortunately, i don't have an ETA as of yet.
If you'd like, i could provide a jar file without the lore stuff - as a temporary alternative until I get to implementing a way to configure the mod.
Thanks for making an issue!

**Comment by onebeastchris** [comment]
good news - i've implemented a config file feature, and it will be available together with some more features shortly. Stay tuned!
You will be able to turn off lore writing, and deciding yourself whether a player head should only be dropped when killed by a player. And another thing, but that'll be here shortly

**Comment by mrniddala** [comment]
That was super fast!
While I encounter this error on my log:

[pool-11-thread-1/ERROR]: Uncaught exception in thread "pool-11-thread-1"
java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4) ~[?:?]
	at net.onebeastofchris.geyserplayerheads.utils.FloodgateUser.isFloodgatePlayer(FloodgateUser.java:16) ~[geyserplayerheads-0.0.5.jar:?]
	at net.onebeastofchris.geyserplayerheads.TextureApplier.<init>(TextureApplier.java:17) ~[geyserplayerheads-0.0.5.jar:?]
	at net.onebeastofchris.geyserplayerheads.events.PlayerJoinEvent.lambda$onSpawn$0(PlayerJoinEvent.java:26) ~[geyserplayerheads-0.0.5.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 6 more

I don't have Floodgate installed, my GeyserMC version is a bit outdated because of a bug, need still to wait. I'm the last Bedrock version behind.

**Comment by onebeastchris** [comment]
As for the config, i should be able to release that in a few short days. As for this error - ideally, you should install floodgate, that will both fix this as well as make the mod more reliable (e.g.: even detecting other prefixes and some other minor stuff)
I'll look into it, thanks!

**Comment by onebeastchris** [comment]
Okay, fixed that issue from happening. Was due to the way i was checking for the floodgate presence - as with the config, it'll be available in the next update.

**Comment by onebeastchris** [comment]
Okay, change of plans - I'll upload a new version to modrinth shortly, that'll add config options (command stuff isn't working yet, no need to change that), and fix the floodgate issue thingy

I'm currently working on an optional (disabled by default) command to get skulls (both bedrock and java) via a simple command, but that's taking longer than expected... maybe next week, maybe later. Don't know yet.

**Comment by mrniddala** [comment]
Great to hear, thanks for your work ❤️

**Comment by onebeastchris** [comment]
It's live now - if you notice anything odd, open a new issue ^^
Thanks for the feature request & the bug report!
